# General Settings
name: Alexey Kasyanchuk
job_title: Senior Software Developer
description: Alexey Kasyanchuk - Senior Software Engineer with 10 years of expiriece in C/C++, Java, Python. I share expiriece.
keywords: C, C++, Java, Python, Performance, Android, Java, Git, Github, StackOverflow, algorithm, Qt, DEgITx, Kasyanchuk, Gitlab
avatar: /degitx.jpg
favicon: /favicon.png
twitter_handler: degitx
analytics_code: G-NF83F10V5F
disqus: degitx
email: degitx@gmail.com

# Social Accounts
social_networks:
-  { name: twitter, url: 'http://twitter.com/DEgITx' }
-  { name: github, url: 'http://github.com/DEgITx' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/alexey-kasyanchuk-60301456/' }
-  { name: stack-overflow, url: 'https://stackoverflow.com/users/1315059/degitx' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "https://blog.degitx.com"
baseurl: ""
plugins:
  - jekyll-sitemap

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

